"""
Interactive setup wizard for screenshot automation
Guides users through configuration and creates config.py
"""

import os
import sys

def print_header():
    """Print welcome header"""
    print("\n" + "="*60)
    print("  Screenshot & OCR Automation - Setup Wizard")
    print("="*60 + "\n")

def print_section(title):
    """Print section header"""
    print(f"\n--- {title} ---")

def get_input(prompt, default=None, required=True):
    """Get user input with optional default value"""
    if default:
        prompt_text = f"{prompt} [{default}]: "
    else:
        prompt_text = f"{prompt}: "
    
    while True:
        value = input(prompt_text).strip()
        
        if value:
            return value
        elif default:
            return default
        elif not required:
            return None
        else:
            print("This field is required. Please enter a value.")

def get_yes_no(prompt, default=True):
    """Get yes/no input from user"""
    default_str = "Y/n" if default else "y/N"
    while True:
        response = input(f"{prompt} [{default_str}]: ").strip().lower()
        
        if not response:
            return default
        if response in ['y', 'yes']:
            return True
        if response in ['n', 'no']:
            return False
        print("Please enter 'y' or 'n'")

def test_button_selector():
    """Guide user to find button selector"""
    print("\nHow to find your button selector:")
    print("1. Open your website in Chrome")
    print("2. Right-click the button → 'Inspect'")
    print("3. Look at the HTML code")
    print("\nExamples:")
    print('  <button id="nextBtn"> → Use ID: nextBtn')
    print('  <button class="next-question"> → Use Class: next-question')
    print('  <button class="btn next"> → Use CSS: button.btn.next')
    print()

def show_selector_examples():
    """Show selector type examples"""
    print("\nSelector Type Options:")
    print("  'id'    - For elements with id attribute")
    print("  'class' - For elements with class attribute")
    print("  'css'   - For CSS selectors (more flexible)")
    print("  'xpath' - For XPath expressions (advanced)")
    print()

def check_tesseract():
    """Check if Tesseract path is needed"""
    print("\nTesseract OCR is required for text extraction.")
    
    if sys.platform == 'win32':
        default_path = r'C:\Program Files\Tesseract-OCR\tesseract.exe'
        if os.path.exists(default_path):
            print(f"✓ Found Tesseract at default location: {default_path}")
            return default_path
        else:
            print("⚠ Tesseract not found at default location")
            has_custom = get_yes_no("Do you have Tesseract installed at a custom location?", False)
            if has_custom:
                return get_input("Enter the full path to tesseract.exe", required=False)
            else:
                print("\n⚠ Please install Tesseract OCR:")
                print("  Download: https://github.com/UB-Mannheim/tesseract/wiki")
                return None
    else:
        print("For Mac/Linux, Tesseract should be in your PATH")
        has_custom = get_yes_no("Do you need to specify a custom Tesseract path?", False)
        if has_custom:
            return get_input("Enter the full path to tesseract executable", required=False)
        return None

def create_config_file(config_data):
    """Create config.py file with user's settings"""
    tesseract_path = config_data.get('tesseract_path')
    tesseract_line = f'TESSERACT_PATH = r"{tesseract_path}"' if tesseract_path else 'TESSERACT_PATH = None'
    
    config_content = f'''# Configuration file for screenshot automation
# Generated by setup wizard

# Website settings
WEBSITE_URL = "{config_data['website_url']}"

# Button selector settings
BUTTON_SELECTOR = "{config_data['button_selector']}"
SELECTOR_TYPE = "{config_data['selector_type']}"

# Automation settings
MAX_CLICKS = {config_data['max_clicks']}
WAIT_TIME = {config_data['wait_time']}

# Tesseract path (leave as None if in system PATH)
{tesseract_line}

# Output settings
OUTPUT_FOLDER = "{config_data['output_folder']}"
OCR_RESULTS_FILE = "{config_data['ocr_results_file']}"
'''
    
    with open('config.py', 'w', encoding='utf-8') as f:
        f.write(config_content)
    
    print(f"\n✓ Configuration saved to config.py")

def show_summary(config_data):
    """Display configuration summary"""
    print("\n" + "="*60)
    print("  Configuration Summary")
    print("="*60)
    print(f"Website URL:      {config_data['website_url']}")
    print(f"Button Selector:  {config_data['button_selector']}")
    print(f"Selector Type:    {config_data['selector_type']}")
    print(f"Max Clicks:       {config_data['max_clicks']}")
    print(f"Wait Time:        {config_data['wait_time']} seconds")
    print(f"Output Folder:    {config_data['output_folder']}")
    print(f"Results File:     {config_data['ocr_results_file']}")
    if config_data.get('tesseract_path'):
        print(f"Tesseract Path:   {config_data['tesseract_path']}")
    print("="*60 + "\n")

def main():
    """Main setup wizard"""
    print_header()
    
    config_data = {}
    
    # Website URL
    print_section("Website Configuration")
    config_data['website_url'] = get_input(
        "Enter the website URL (e.g., https://example.com/quiz)",
        default="https://example.com"
    )
    
    # Button selector
    print_section("Button Selector Configuration")
    test_button_selector()
    
    config_data['button_selector'] = get_input(
        "Enter the button selector (e.g., nextBtn or button.next)",
        default="button.next"
    )
    
    show_selector_examples()
    config_data['selector_type'] = get_input(
        "Enter the selector type",
        default="css"
    ).lower()
    
    # Automation settings
    print_section("Automation Settings")
    
    max_clicks_str = get_input(
        "How many times should the button be clicked?",
        default="10"
    )
    config_data['max_clicks'] = int(max_clicks_str)
    
    wait_time_str = get_input(
        "How many seconds to wait between clicks?",
        default="2"
    )
    config_data['wait_time'] = int(wait_time_str)
    
    # Output settings
    print_section("Output Settings")
    
    config_data['output_folder'] = get_input(
        "Folder name for screenshots",
        default="screenshots"
    )
    
    config_data['ocr_results_file'] = get_input(
        "Filename for OCR results",
        default="ocr_results.txt"
    )
    
    # Tesseract configuration
    print_section("Tesseract OCR Configuration")
    config_data['tesseract_path'] = check_tesseract()
    
    # Show summary
    show_summary(config_data)
    
    # Confirm and create
    if get_yes_no("Create config.py with these settings?", True):
        create_config_file(config_data)
        
        print("\n✓ Setup complete!")
        print("\nNext steps:")
        print("  1. Make sure Tesseract OCR is installed")
        print("  2. Run: python screenshot_automation.py")
        print("\nTo change settings later, edit config.py or run this setup again.")
    else:
        print("\nSetup cancelled. Run 'python setup.py' again to configure.")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
        sys.exit(0)
    except Exception as e:
        print(f"\n\nError during setup: {e}")
        sys.exit(1)
